name: Worldathletics Scraper

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 5 * * *'  # Schedule to run at 5 AM UTC every day

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Edge
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget https://packages.microsoft.com/keys/microsoft.asc
        sudo apt-key add microsoft.asc
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
        sudo apt-get install -y wget unzip xvfb

    - name: Verify Edge Installation
      run: microsoft-edge --version

    - name: Run scrape script
      env:
        DISPLAY: ":99.0"
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        Xvfb :99 -ac &
        sleep 3 # Give Xvfb some time to start
        python insert_recent_data.py

        

